//! Shared gRPC wire contract for the Canopy backend.
//!
//! This facade re-exports the immutable Prost and Tonic SDKs generated by the
//! Buf Schema Registry for `buf.build/pandawave/canopy-api`.

pub use canopy_api_prost::canopy::v1::*;
pub use canopy_api_tonic::canopy::v1::tonic::*;
